apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config
  namespace: default
  labels:
    app: nginx-webapp
data:
  PID_NAME: "nginx"
  MAIN_CONTAINER_NAME: "nginx"
  MOUNT_PATH: "etc/nginx/data"


