kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/persistent-volume"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi