apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-app
  name: nginx-hasher-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-app
        hasher-webhook-process-name: "nginx"
        hasher-webhook-injector-sidecar: "true"
    spec:
      serviceAccountName: hasher
      shareProcessNamespace: true
      containers:
        - name: nginx
          image: nginx:latest
          stdin: true
          tty: true