apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-webapp
  name: nginx-webapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-webapp
    spec:
      serviceAccountName: hasher
      shareProcessNamespace: true
      containers:
        - name: nginx
          image: nginx
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /etc/nginx/data
              name: nginx-persistent-storage

        - name: hasher-container
          image: upgrade:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: postgres-kuber-hasher-secret
          command: [ "sh","-c","pid=$(pidof -s $PID_NAME);echo $pid;echo $MY_NODE_NAME; echo $MY_POD_NAME; ./sha256sum -d ../proc/$pid/root/etc/nginx/data;"]
          env:
            - name: PID_NAME
              value: "nginx"
#            - name: PID
#              valueFrom:
#                configMapKeyRef:
#                  name: special-config
#                  key: pid
#              value: "PID=$(pidof -s $PID_NAME)"
            - name: FOLDER_PATH
              value: "../proc/$pid/root/etc/nginx/data"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                 fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.name


            - name: DEPLOYMENT_NAME
              value: "nginx-webapp-dep"
          resources:
              limits:
                memory: "50Mi"
                cpu: "50m"
#          livenessProbe:
#            exec:
#              command: [ "sh","-c","./sha256sum -l" ]
#            initialDelaySeconds: 2
#            periodSeconds: 30
#            failureThreshold: 1
#            successThreshold: 1
#            timeoutSeconds: 10
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          stdin: true
          tty: true
      volumes:
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: nginx-persistent-volume-claim