apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-webapp
  name: nginx-webapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx-webapp
    spec:
      serviceAccountName: hasher
      shareProcessNamespace: true
      containers:
        - name: nginx
          image: nginx
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /etc/nginx/data
              name: nginx-persistent-storage


        - name: hasher-container
          image: upgrade:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: special-config
            - secretRef:
                name: postgres-kuber-hasher-secret
          command: [ "sh","-c","pid=$(pidof -s $PID_NAME); ./sha256sum -d ../proc/$pid/root/$MOUNT_PATH;"]
          env:
            - name: MY_POD_NAME
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
          resources:
              limits:
                memory: "50Mi"
                cpu: "50m"
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          stdin: true
          tty: true
      volumes:
        - name: nginx-persistent-storage
          persistentVolumeClaim:
            claimName: nginx-persistent-volume-claim