apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-app
  name: php-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: php-app
        #tcpdump-sidecar: "true"
    spec:
      serviceAccountName: hasher
      shareProcessNamespace: true
      containers:
        - name: php
          image: php
          stdin: true
          tty: true
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command: ["sh","-c","ps=$(ps aux);echo $ps"]
