apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  shareProcessNamespace: true
  containers:
    - name: nginx
      image: nginx
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /etc/nginx/data
          name: nginx-persistent-storage

    - name: hasher-container
      image: upgrade:latest
      imagePullPolicy: Never
      envFrom:
        - secretRef:
            name: postgres-kuber-hasher-secret
        - configMapRef:
            name: special-config

      command: [ "sh","-c"," echo $(POD_NAME), $POD_NAMESPACE, $NAME_IMAGE_TAG, $SPECIAL_LEVEL" ]
      #[ "sh","-c","pid=$(pidof -s $PID_NAME);echo $pid; echo $MY_NODE_NAME;echo $MY_NODE_NAME;  ./sha256sum -d ../proc/$pid/root/etc/nginx/data;" ]
      env:

        - name: POD_NAME
          valueFrom:
              fieldRef:
                fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
              fieldRef:
                fieldPath: metadata.namespace


      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
      #          livenessProbe:
      #            exec:
      #              command: [ "sh","-c","./sha256sum -l" ]
      #            initialDelaySeconds: 2
      #            periodSeconds: 30
      #            failureThreshold: 1
      #            successThreshold: 1
      #            timeoutSeconds: 10
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE
      stdin: true
      tty: true
  volumes:
    - name: nginx-persistent-storage
      persistentVolumeClaim:
        claimName: nginx-persistent-volume-claim

  restartPolicy: Always