apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: kuber-hasher-svc                           # Name of the resource
  labels:                                           # Labels that will be applied to the resource
    app: kuber-hasher
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:                                         # Selects any Pod with labels `app=fullstack-postgres,tier=postgres`
    app: kuber-hasher
    tier: postgres