apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: php-app
  name: php-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: php-app
        webhook-injector-sidecar: "true"
    spec:
      serviceAccountName: hasher
      shareProcessNamespace: true
      containers:
        - name: php
          image: php:latest
          stdin: true
          tty: true
          volumeMounts:
            - name: config
              mountPath: "/etc/config"
              readOnly: true
      volumes:
              - name: config
                configMap:
                  name: config
                  items:
                    - key: php
                      path: php
