kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: k8s-webhook-injector
spec:
  selector:
    component: k8s-webhook-injector
  ports:
    - name: http
      port: 443
      targetPort: 8443