---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-k8s-webhook-injector
  namespace: default
data:
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGekNDQXYrZ0F3SUJBZ0lVYm5qQjdDSkhVK2RCb2NJUHQvbzg4Ry9HZW93d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdOakkyCk1qSXpPVEF3V2hjTk5ESXdOakl4TWpJek9UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLVk1JTG1KCkZQUG5wbmNycjkrUVhTSXF2UGNtY2kvaXpweEJFcjlNR1hUdzNBSEx6ZEpYUFlrT3UxYTZOUnFicjF2SlUwQ3MKYmx6Q1BSWStIbWJFYlVxcHcyV3N0a3F5eStvVkdWb09WM1FXb05VYTl3L1pacjV5QTJ5NG1jUWpXTUEvd0w3VApLWnU3Skd4aEVicHB5K3ZlckwrUzdDekd5K0dGd3RHdHhLcnNsaGNCZ3RtbUtKWDNJWTFodllaT3RxaHJOdlYvCnF3SkVuQ3M1MkE0MEVlU1B6dVFIbUQ2cFJGRnMvdTl0czcxSVZ2YjFVcTU3MVBVWExHUDBBMVpTM3NNaFk5b0oKai9EcXc2ZldDRk9NSE5yQjZrS0J5M1VNUERoK04zbFdyV3IraGdiOTRpemxRalNtU1lOakh4Qy9Vc3FSTDVmVwpSQWhZRXI2aUFFeFAzVTBDQXdFQUFhT0I1RENCNFRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZLeVYKOXVIMXZIR3BPcThSYnR4cnk1UlkxUUpXTUlHQ0JnTlZIUkVFZXpCNWdoUnJPSE10ZDJWaWFHOXZheTFwYm1wbApZM1J2Y29JdWF6aHpMWGRsWW1odmIyc3RhVzVxWldOMGIzSXVaR1ZtWVhWc2RDNXpkbU11WTJ4MWMzUmxjaTVzCmIyTmhiSUlnYXpoekxYZGxZbWh2YjJzdGFXNXFaV04wYjNJdVpHVm1ZWFZzZEM1emRtT0NDV3h2WTJGc2FHOXoKZEljRWZ3QUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBcTNEK0JScEdOcEZ6ckQ0aGpuYTNKbmRxY2Z3NwowOWlOQ0Y0VTE2SU9Vb1VhYkNEcVVxZ2M0VHQ2TS9GSFlsanFBR2JjZk5lek1EM3N3VU9PMWljNmF4aXZIVDROCnFUVzBYSlFZNHVsRk9JZUlKTEZCUlExVTJ5S2xqVG5TUzgwRk1xNU82RzkxZTY5TURoTkdRdm9iMWNVSC9RU2gKZ3gyZ3RadzliazRmNTV0L04wUVRTS0hKdExscWkrZEZQbFp4VzV1ZTU1QVZNL1craTNaR2l5LzFkSVdCWUFhdwpTZll6RDVHbjlWR2tNVzNoWTdLVU4vbEU2TS8vZ210RW52SXU5a2piZGZ2ZXJ6OFBiS0Q1TVUxOEJpelN4eDNICjhHcXdxWlAwYkpvdWNLeHhTcXJJQnQ5SFM5elBGOVVTWThkUUdueHNlblkzTlVBOTQ1R2JPSXMyVWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBcFV3Z3VZa1U4K2VtZHl1djM1QmRJaXE4OXlaeUwrTE9uRUVTdjB3WmRQRGNBY3ZOCjBsYzlpUTY3VnJvMUdwdXZXOGxUUUt4dVhNSTlGajRlWnNSdFNxbkRaYXkyU3JMTDZoVVpXZzVYZEJhZzFScjMKRDlsbXZuSURiTGlaeENOWXdEL0F2dE1wbTdza2JHRVJ1bW5MNjk2c3Y1THNMTWJMNFlYQzBhM0VxdXlXRndHQwoyYVlvbGZjaGpXRzloazYycUdzMjlYK3JBa1NjS3puWURqUVI1SS9PNUFlWVBxbEVVV3orNzIyenZVaFc5dlZTCnJudlU5UmNzWS9RRFZsTGV3eUZqMmdtUDhPckRwOVlJVTR3YzJzSHFRb0hMZFF3OE9INDNlVmF0YXY2R0J2M2kKTE9WQ05LWkpnMk1mRUw5U3lwRXZsOVpFQ0ZnU3ZxSUFURS9kVFFJREFRQUJBb0lCQURBbUZybzB0Z2UrQ0gxYQpHbWJTMUc0cGFOWE5PeUc3dlZkQ2xVVm4wMXArOW5jSGVMSzJldFE3bUZKUTl6c0M4bmVZRTBvWmNDUlE2QjVjCmhkcUZpUmhnanV4RS9PeVJYRmlaUU1NOHZqaXdoclRNbi83YjR0UEN2a0NqSFJkRy9Ja3ppTitNL3VmQUFZSVkKWEdPaWdhWDVQUFNveFdiZG1YSGQxcnZoRkJKOVUvb3BTdjNheURrSGgrRE50SFBjd1I1d2huVFBBcDV0dVZqNworM09sbExVdk1EWGlxL0xmdUExU3dnUy9ObWhnN21TdGVJQk1qWlh2WnozMk5WRTNTZzdxcFRDTnE1Vkc2ZjhOCmExMjg0YSs2NmcxdjZDRFlnaSs4cTZEMDNxS2JFMmpKOHY0eXg1M2tiKzdIU3kwa085bUR3QVF5ellhSThQUFgKVHYyNmNIa0NnWUVBeStNaWQwNGgxcGg2QnhxQ0tYU1lyalNxdFdvK1JpL0ZLUHNRN0pQbDVubWdxSDZMMmlFSgpvaGJSNSs4ZDd3Zy9lek1QTjlzNXpIMGdZYlg3L1Y3Yjd5czZsNzJYV0tiS2pZUExScXRrQWcxUmt6OFJGTndxCnJ6UkxybnE5amh2TllsZVNRdEt2S25OMEJId25sVVNIaXFveXBYOWNyMmY0Y1hwcC9vd3E4bU1DZ1lFQXo0djEKZ1V3eWRxN1Q5bEU0TFFnRFF5d3pPenJoMEZvN0hXRmlWaGZ3L2JTalNJMFZ6UUhRdXJPd1VFVHRwT2Ridis1VQpscllkN3psaEF1QnMzTUJrOHY4dFhETmRzbFFZcUd3eVQ1TVNrMkRqa0J2MFlVeG9ZN3lUWFhGOVhtWFZDY2RUCmJ2ZHZZaXdNUGFMb2VmRHFmOFRCcFpaT0RnMExFb1NxSGJ5eEtJOENnWUJIQytYMXR1YzV0VFpJaFdjMzlPWkQKUmh6NlRJUll4c3FvUmh5V284N242aGdldnNJVEI1SW94bFRzd2prbkV6T3p4WTRYQTdCM1hsN0xUYlA2alhTTQpPZjhYNHp2NjYxd0h4aFl1a1FpdllsNjd0YTFKSEpOUExDVDNMdFFnMGZWV3dIYzZDOXA0SzNVUkh3WllFR0krCjRxSDFZNVV6bGtKUG9MMlFzdDFBU3dLQmdBM0J3U3dvMk05MUZ5ZWtpb3l4azBYSWtEekUwbUwxR0NZQ1pubysKYkFMbERrMm96R0VpVmF1S2JZMWtoRHdCK2RybStVUmtIZWZWYmRDNi8zeENaRzZXNjNMSkZOVFZMaTA3dnJuMwpqYXVuS0c1TTdBM20rcVJodzRMV0d2RSszcmdmTmpDTXhoMUR2aXYzdUdFY3p1NVpKRnpOY2E4TXZrY2o5QUswCmx5bVJBb0dBUDJVTTgwWERiRE9SdEVWQzUzQldITFpEcEh1cGplbE1JY3BWOTBYcUNDaFZXaHVaa3lMVG5qK0IKamR0bjFDN0VBZTgweWFiK05HSFpha1JobTN3eE1tUm5DMnNNdER1NzVYMllvVnFIby9MK0cwNTViNWhubXhESAp5K29zcWlDQ2s0Z0hxOUxadENmcklYMFVUdEhvNWJGaWMrVlBDaUxmZ2RKSXBrWEQrS1U9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webhook-injector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: k8s-webhook-injector
  template:
    metadata:
      labels:
        component: k8s-webhook-injector
    spec:
      containers:
        - name: k8s-webhook-injector-ws
          image: webhook:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8443
          volumeMounts:
            - name: ssl-k8s-webhook-injector
              mountPath: /ssl
      volumes:
        - name: ssl-k8s-webhook-injector
          configMap:
            name: ssl-k8s-webhook-injector
---

kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: k8s-webhook-injector
spec:
  selector:
    component: k8s-webhook-injector
  ports:
    - name: http
      port: 443
      targetPort: 8443