---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-tcpdump-webhook
  namespace: default
data:
  server.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVCekNDQXUrZ0F3SUJBZ0lVRzdLa1JKbzJ1WXhLcXBUYmtPSHRLN0NTaUE0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdOakl5Ck1UTXdOekF3V2hjTk5ESXdOakUzTVRNd056QXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOc0JRd0pVClhacjN5RDlYbWY0Y21FNW9ZTmUzRmxQVmFnY25rcWFyTjlHRTViN1l1N0NpUE1ya0JhWHNONXpxQ2E3T0E4VUoKellUcUk1RExQOWk3YldDbGxZVGEyVWJuZTZiaXNYRFoxbXJ2dEtSaCtUZThydm1uNXkxWXZrUGRNK0ZMV0F4KwpXVEluMmZSczhlbzlaOHl5OXlyZkRrdmVhcEVnSi9MYWlrcEF5dEZUN1hZTjB4Y3k1VkJFaWo1YXpJdmU4RGZHCjhIRCtFb1dPZlRsK1NzV05IS3VRZ1IvaU9vcUtldkQwalNXRkRpaW9JbFZxL2h1MVMxOThIbWQ3VlNRY2hyd0EKN1FIMHE0Z1dIODlrbTJmME9NeEdqK0tUaTFCbWRlK0FFZjJKQlVxMlAvWmt0aHlvVlMvdTFYVlJzeXZ4VmI4OQp2SFJiS2kwOTNLZ3lNbmNDQXdFQUFhT0IxRENCMFRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3CkZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZQcjEKNG5VWmZ2VHRvQzI1ZlV3TThqRmdkUFROTUhNR0ExVWRFUVJzTUdxQ0QzUmpjR1IxYlhBdGQyVmlhRzl2YTRJcApkR053WkhWdGNDMTNaV0pvYjI5ckxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd5Q0czUmpjR1IxCmJYQXRkMlZpYUc5dmF5NWtaV1poZFd4MExuTjJZNElKYkc5allXeG9iM04waHdSL0FBQUJNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDSDgvRUh5czFIeGlMeU04ZStmdkZYd3kzL1NVZXcrS2E2NTZuSGYrZUU4dXExTktMNgpGTE5wZGI3WjBaUVZoZnBIeEFRL01TbGlpeEE5MnY2SUJja0cvY1Fwb28yOWs2Y01ZSmRBNG8zSSs5WVlOV1ZyCnhvQmt5Qi9aTDJkV0RpZVZmT1FUanJ2RWU5SjZpYlRpcEhHWEhRS0ZtaVY5WjM0em9SaDNGN2dDNWdxakZ0K3EKN3V1Mm9nSVJnZXkxK0RPamtqNHBDcGlhV096UWxxZkExZG9BdjNRVUFxYm10N3hlYVlvbEhWZEgrc0t3ZHlLUgpxaXhtNXlIMWJtOXdBYk1hb1Qzc3lpODdMdUJuZVZQaXFROGorTGRNU3lrVk9hN25QWmRsR2wrL1h1allIbFRFClNPOVdRUzVSams2eFBMeVRVeUt6QlR4YXV1Y2lKd1BRYWtJUgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  server.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBMndGREFsUmRtdmZJUDFlWi9oeVlUbWhnMTdjV1U5VnFCeWVTcHFzMzBZVGx2dGk3CnNLSTh5dVFGcGV3M25Pb0pyczREeFFuTmhPb2prTXMvMkx0dFlLV1ZoTnJaUnVkN3B1S3hjTm5XYXUrMHBHSDUKTjd5dSthZm5MVmkrUTkwejRVdFlESDVaTWlmWjlHeng2ajFuekxMM0t0OE9TOTVxa1NBbjh0cUtTa0RLMFZQdApkZzNURnpMbFVFU0tQbHJNaTk3d044YndjUDRTaFk1OU9YNUt4WTBjcTVDQkgrSTZpb3A2OFBTTkpZVU9LS2dpClZXcitHN1ZMWDN3ZVozdFZKQnlHdkFEdEFmU3JpQllmejJTYlovUTR6RWFQNHBPTFVHWjE3NEFSL1lrRlNyWS8KOW1TMkhLaFZMKzdWZFZHeksvRlZ2ejI4ZEZzcUxUM2NxREl5ZHdJREFRQUJBb0lCQUVHRlRCM3JUYUhxVmErVgpyczJXa242S3ZjWnIwVE05bXg0TzJkSWhVVzdPbXNtUkgvNEZXN2k3cFhEeGplWFZJeFo0TGlxSjkwRzNwdkpQCnpJY3o4OUpCVjgxS2lFeXRQcEk4S2lnQUZDVWtGK0JDSzRSZ1g5enpQYmVVWUQvL2N1RUpZSXRFVmIwcXJRdHkKZUtIQ3cwWTdtTFRyek9RbjQ2d05lY1l2V2NaQ3RGN0NtZVRIVmpzWWNyZ1NZMnRWakdpOWg4ZmRiSy9LeHhHTwpBdmp0bXZEUUpXWFdoSC9FUDd3OVJJTHZIYXJ2UXFydGJqRyszajYzT1d6emRDL3NtSzR2b2dOM3J6dmhIb0NKCjdpL1FDcHlKRDJNUUtmSlN6clRUM3pNaVVrUzF3MXZkQy90TnVERHJ2SU1RMFg3NVIxdlFlRnlwMS9GZVpDRE0KMU1lZjRJRUNnWUVBNDAzRkFGMnNpL0JJTlVnam13NlpyVklaK3QvUUFkL1RqTk1FMkUxUFZkMWtlNUp3UmJwTwpEK3RTZHd0RTF0YStqNDNuclMxVFM5aHJhblpLeGg4eWdZdnlyT3h3TVNxYzZmTVdCNXA0QnNqRXg3SE5NT3RPCldtOExuRDR4SUVvWDMwdkM0aFZXTy94OHlyZGlqelM3b3NXSG1HNmd0MFpwVWFBNzZLWFZKYmNDZ1lFQTlxZEkKQys0TU1DNE13UzVvdWRkUFJha1FkU21GQzUxMWxoUTlKdW9jNmduUlFJVGJVS21IUmVxMk9TT2xCaVhldnVzdAp6Z1JyMVR2WEdMTUZ6S2FLNlRTeHl3cmlvTjg4eHI1c1ZrZnVkOTBkNjhGUkZBcCtKSzFiS2RJV0swRDgzYVF0CkYzL3JiVUd2N2NURWtTVytyYjVUT2twaCtIV28rSUxDUGh6QldVRUNnWUVBeHN3dnJpQS9WcXl5R3BlYlBIUEsKaUVHMEl5dzRHa3VPRkM1Q29JTU5EZ1h4YWZvclkzQ0w4WFJZelhEM3BnWnU1OUt1ZTFHVzlsQ3pzWXIvM3NOTwpRdXNKTmFBY2g0UERkUUY3bE83T1p2Q1UyaXB4VVlXYkk1RFhVTEU3K2dlVFZXSkhjY0JEaVhkTUZXZktOWUZqClVmcjhtcDYyeFZRNXJJQTlwVDNVYTRVQ2dZRUFqclVPakVoNHFNK2I5WkdDYWpQVzI3a0xtcDRoS2kwNlFWRUkKYUtGL2hUR1U3ajF3SHVWWExPNjE2NjFoNTRLMXM4U2lSZFp0Qlh5UDRPeURhSHJiV0Q1eXQ4VmVoakZqR3FKRwpVRTFoL2R2aldlb0puUXpOR3k5cDFYS0YvUlNtdVI0cU1MU0VaRHhqSzdCekFuL1NLUGc3Y3poaUlyMEF2SGY3CkpyREFkWUVDZ1lFQXBISTNXNjNxZXNqUU1nUDQ4Z1JaRnpFaWZ5cFhQTTEwVFIrb3Z4ZkllMlhqZjJYRGlIOTkKYlowV3VzYytYWXgrMUgwd1F3a3cwRTVFc21oaUxkcWhMWGlxVFhiNEtJR1h6dkIzY0RycWh4cjZjUTJycGVYdAp4aGdjN3dZR3c3T1IxdkY5Z0p0dGtKNkFGSTB1eGgySnpFdmQwQkVHZmZVcWhuYzlUZzhxVzAwPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcpdump-webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: tcpdump-webhook
  template:
    metadata:
      labels:
        component: tcpdump-webhook
    spec:
      containers:
        - name: tcpdump-ws
          image: webhook:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8443
          volumeMounts:
            - name: ssl-tcpdump-webhook
              mountPath: /ssl
      volumes:
        - name: ssl-tcpdump-webhook
          configMap:
            name: ssl-tcpdump-webhook
---

kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: tcpdump-webhook
spec:
  selector:
    component: tcpdump-webhook
  ports:
    - name: http
      port: 443
      targetPort: 8443