apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: k8s-webhook-injector
webhooks:
  - name: k8s-webhook-injector.default.svc.cluster.local
    failurePolicy: Fail
    clientConfig:
      service:
        name: k8s-webhook-injector
        namespace: default
        path: "/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkRENDQWx5Z0F3SUJBZ0lVSUFNbEV5WUlhTU5pKzJYd3JsdlJqblhZblZNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1VqRUxNQWtHQTFVRUJoTUNRVlV4RURBT0JnTlZCQWdUQjBWNFlXMXdiR1V4RWpBUUJnTlZCQWNUQ1UxbApiR0p2ZFhKdVpURVFNQTRHQTFVRUNoTUhSWGhoYlhCc1pURUxNQWtHQTFVRUN4TUNRMEV3SGhjTk1qSXdOakkyCk1qSXpPVEF3V2hjTk1qY3dOakkxTWpJek9UQXdXakJTTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUNCTUgKUlhoaGJYQnNaVEVTTUJBR0ExVUVCeE1KVFdWc1ltOTFjbTVsTVJBd0RnWURWUVFLRXdkRmVHRnRjR3hsTVFzdwpDUVlEVlFRTEV3SkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNMEZFQUhMCmloZFhhNWE4aXU4V1JScE1meXVsTHRGRU1uY01sbklnWFpKMkZPUWlpNGxoeUtSQUw0RGpwUTNQNFJPbmJ3WEMKQlptYm50aDAxY3pNaVpDNkV4UHh6dnIxazEzV04xVHg1c25lejNLdlVORE9lUTdiV3Zidm9WZisxa3E0VFpOOQpnL2w0dFZGc2xwdjhOU2x1SUZVYVdLRDViUTBOQ3pIZzhMNzEwZHIxWmVvUHVOd0tuNFR1VFV2UVh3ZzV5cW1HCmc0cUVKZFlSbEJjQlFWT2tmVEcyQnMwN0R1bWxDRVg0Ny9YVEFhTXBNd3hVMTZNNnhUR3RxODNxdFlNTUlhdlgKS1FKUDdGekI0ZSsyVk5vYWFGLzJFaGl5ZkcwbEQyOTNSbzJ3T3RReDZuVWV1dWxSUzEvV0w2bTRGdzAxL1NVUQo3bWNaV0FMK01kK3BkemtDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGCk1BTUJBZjh3SFFZRFZSME9CQllFRk5QR0VSSDV4VjJDTTZTVEJUVkdXeGFGb3lWcE1BMEdDU3FHU0liM0RRRUIKQ3dVQUE0SUJBUUE1Q3pZTDhYNlhmS3VDQnA2OWJkWFRHUG00Q3JKeW1ueGhPbUFtRjFLODdSTU9NbE5lR2pZYQpNWVQ5enloRXE4KzZTMDAzV1NuQlZ0cU5ML2FRTnljNmFFYWJINUhhNjZodHpQd0NTRndDU2FsbVlqU1JuL2txCnNQQXN2WTZlZ2d0MmwwZWpIT1ZLZHRxc2xoemU5SEJ5K2Uxd2Y0bFVwUkZLZElLdlRKQ21jZ2MveFVBK0dxM3gKQzRsRjRXNDFhRmVFYm1QQlhGSFc4SmlJbFZSTTh0ai9nS1V2R1gvOWJNYmJZdytHSlNMdUZRUHMvcitCczI2NQpIOG53TThHR1J6NzhIL2dCTGxDc1V1MnNCWDV6V0o4RTZKR0hrK3FUMGRhby9XQ0M3Ry9DbHNXUTBUb0VWOWk2CkFna1poa0MrMlhBTnovRkh4ZWhzaVY2OEZqYkt2ZUJjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 5